#!/bin/bash
set -euo pipefail
##############################################################################
# ZZCOLLAB PROJECT MODULE (Consolidated)
##############################################################################
#
# PURPOSE: Project structure creation and R package setup
#          - Directory structure (zzcollab framework)
#          - R package files (DESCRIPTION, NAMESPACE, tests)
#          - Analysis templates
#          - Development tools (Makefile, .gitignore)
#
# DEPENDENCIES: core.sh, templates.sh
##############################################################################


#=============================================================================
# DIRECTORY STRUCTURE
#=============================================================================

create_directory_structure() {
    log_debug "Creating directory structure..."

    # Base directories, always present: analysis workspace, docs, CI.
    local base_dirs=(
        "analysis"
        "analysis/data"
        "analysis/data/raw_data"
        "analysis/data/derived_data"
        "analysis/report"
        "analysis/figures"
        "analysis/tables"
        "analysis/scripts"
        "docs"
        ".github"
        ".github/workflows"
    )
    # R-package directories, skipped for a bare/prose compendium (R9).
    local pkg_dirs=(
        "R"
        "man"
        "tests"
        "inst"
        "inst/tinytest"
        "vignettes"
    )

    local dirs=( "${base_dirs[@]}" )
    if [[ "${ZZCOLLAB_BARE:-false}" != "true" ]]; then
        dirs=( "${pkg_dirs[@]}" "${base_dirs[@]}" )
    fi

    for dir in "${dirs[@]}"; do
        if ! mkdir -p "$dir"; then
            log_error "Failed to create directory: $dir"
            return 1
        fi
    done

    log_success "Created ${#dirs[@]} directories"

    # Write project marker for _zzcollab_root() detection.
    touch .zzcollab
}

#=============================================================================
# R PACKAGE FILES
#=============================================================================

create_r_package_files() {
    local pkg_name="${PKG_NAME:-$(basename "$(pwd)")}"

    log_debug "Creating R package files..."

    # DESCRIPTION
    if [[ -f "${ZZCOLLAB_TEMPLATES_DIR:-}/DESCRIPTION" ]]; then
        install_template "DESCRIPTION" "DESCRIPTION" "DESCRIPTION file"
    else
        create_description_file "$pkg_name"
    fi

    # NAMESPACE
    local namespace_content='# Generated by roxygen2: do not edit by hand
exportPattern("^[[:alpha:]]+")'
    create_file_if_missing "NAMESPACE" "$namespace_content" "NAMESPACE file"

    # LICENSE: year/holder from the resolved config, else current year/author
    local license_year="${CONFIG_LICENSE_YEAR:-$(date +%Y)}"
    local license_holder="${CONFIG_LICENSE_HOLDER:-${CONFIG_AUTHOR_NAME:-${AUTHOR_NAME:-Author}}}"
    local license_content="YEAR: ${license_year}
COPYRIGHT HOLDER: ${license_holder}"
    create_file_if_missing "LICENSE" "$license_content" "LICENSE file"

    log_success "R package files created"
}

create_description_file() {
    local pkg_name="$1"
    # Fallback path (templates/DESCRIPTION absent); mirror its config wiring.
    local content="Package: ${pkg_name}
Title: ${pkg_name} Data Analysis
Version: 0.0.0.9000
Authors@R:
    $(render_authors_r)
Description: Data analysis workspace for ${pkg_name}.
License: ${CONFIG_LICENSE_TYPE:-GPL-3}
Encoding: ${CONFIG_RPACKAGE_ENCODING:-UTF-8}
Roxygen: list(markdown = TRUE)
RoxygenNote: ${CONFIG_RPACKAGE_ROXYGEN_VERSION:-7.3.2}
Suggests:
    tinytest (>= 1.4.0)"
    create_file_if_missing "DESCRIPTION" "$content" "DESCRIPTION file"
}

#=============================================================================
# TEST INFRASTRUCTURE
#=============================================================================

create_test_infrastructure() {
    log_debug "Creating test infrastructure..."

    local pkg="${PKG_NAME:-$(basename "$(pwd)")}"

    # tinytest runner: runs inst/tinytest/ tests when the package is checked
    local tinytest_runner='if (requireNamespace("tinytest", quietly=TRUE)) {
  tinytest::test_package("'"$pkg"'")
}'
    create_file_if_missing "tests/tinytest.R" "$tinytest_runner" "tinytest runner"

    # Example test file (tinytest style: bare expectations, no test_that wrapper)
    local test_example='expect_true(TRUE)'
    create_file_if_missing "inst/tinytest/test-basic.R" "$test_example" "example test"

    log_success "Test infrastructure created"
}

#=============================================================================
# ARCHETYPE SYMLINK TOPOLOGY
#=============================================================================

# create_relative_symlink <linkpath> <relative-target>
# Idempotent (ln -sfn), tolerant of filesystems without symlink support so a
# scaffold on such a platform warns rather than aborting.
create_relative_symlink() {
    local link="$1" target="$2"
    mkdir -p "$(dirname "$link")"
    if ln -sfn "$target" "$link" 2>/dev/null; then
        log_debug "symlink: $link -> $target"
    else
        log_warn "Could not create symlink $link -> $target (filesystem may not support symlinks)"
        return 1
    fi
}

# create_archetype_symlinks <archetype>
# Create the symlink topology a publishing archetype needs. A blog post's
# source lives in analysis/report/index.qmd but must appear as index.qmd at the
# compendium root so a parent Quarto site renders posts/<slug>/index.qmd; assets
# are symlinked at both the root and the report level so they resolve whether
# the post renders from the site or in place.
create_archetype_symlinks() {
    local archetype="$1"
    case "$archetype" in
        blog)
            create_relative_symlink "index.qmd" "analysis/report/index.qmd"
            create_relative_symlink "data"      "analysis/data"
            create_relative_symlink "figures"   "analysis/figures"
            create_relative_symlink "media"     "analysis/media"
            create_relative_symlink "analysis/report/data"    "../data"
            create_relative_symlink "analysis/report/figures" "../figures"
            create_relative_symlink "analysis/report/media"   "../media"
            ;;
    esac
}

#=============================================================================
# ARCHETYPE SPEC + ENTRY SCAFFOLDS
#=============================================================================

# Declarative archetype spec. archetype_spec <archetype> <field> echoes the
# value; one engine (apply_archetype_scaffold) consumes it. Fields:
#   render_entry   which entry scaffold to run (dispatch key)
#   symlinks       symlink set name (see create_archetype_symlinks) or 'none'
#   render_target  the render-gate entry path (used by tooling / docs)
# The R-package skeleton is orthogonal to the archetype (ZZCOLLAB_BARE, R9),
# so it is not a spec field.
archetype_spec() {
    local a="$1" field="$2"
    case "${a}.${field}" in
        manuscript.render_entry) echo "report_rmd" ;;
        analysis.render_entry)   echo "analysis_index" ;;
        blog.render_entry)       echo "blog_index" ;;
        book.render_entry)       echo "book" ;;
        simulation.render_entry) echo "simulation" ;;
        package.render_entry)    echo "none" ;;
        *.render_entry)          echo "analysis_index" ;;

        blog.symlinks)           echo "blog" ;;
        *.symlinks)              echo "none" ;;

        manuscript.render_target) echo "analysis/report/report.Rmd" ;;
        analysis.render_target)   echo "analysis/report/index.qmd" ;;
        blog.render_target)       echo "analysis/report/index.qmd" ;;
        book.render_target)       echo "analysis/book" ;;
        *.render_target)          echo "" ;;
    esac
}

# manuscript: bookdown PDF report.Rmd + bibliography + CSL.
_scaffold_report_rmd() {
    install_template "report.Rmd" "analysis/report/report.Rmd" "report template" 2>/dev/null || true
    install_template "references.bib" "analysis/report/references.bib" "bibliography" 2>/dev/null || true
    # The report YAML references ../templates/<csl>; ship it so the default
    # report renders without a missing-resource error.
    install_template "statistics-in-medicine.csl" "analysis/templates/statistics-in-medicine.csl" "citation style (CSL)" 2>/dev/null || true
    log_success "Report scaffolded (report.Rmd)"
}

# analysis (R4): a Quarto index.qmd (HTML-first, PDF too) instead of bookdown.
_scaffold_analysis_index() {
    local doc='---
title: "Analysis"
author: "'"${AUTHOR_NAME:-Your Name}"'"
date: "'"$(date +%Y-%m-%d 2>/dev/null || echo 2026-01-01)"'"
format:
  html:
    toc: true
    code-fold: false
  pdf:
    documentclass: scrartcl
bibliography: references.bib
---

# Introduction

Write the analysis here. Reference figures in `../figures` and data in
`../data`.'
    create_file_if_missing "analysis/report/index.qmd" "$doc" "analysis document (index.qmd)"
    create_file_if_missing "analysis/report/references.bib" \
        "% Add BibTeX entries here; cite them with [@key]." "bibliography"
    log_success "Analysis document scaffolded (index.qmd)"
}

# blog: single-post compendium (index.qmd in analysis/report/ + symlinks are
# applied by the engine via create_archetype_symlinks).
_scaffold_blog_index() {
    mkdir -p analysis/media/images
    local post='---
title: "First post"
author: "'"${AUTHOR_NAME:-Your Name}"'"
date: "'"$(date +%Y-%m-%d 2>/dev/null || echo 2026-01-01)"'"
categories: [r]
description: >
  One-sentence summary of the post.
image: media/images/hero.png
format:
  html:
    code-fold: false
draft: true
---

Write the post here. Reference images as `media/images/<file>` and data
as `data/<file>`.'
    create_file_if_missing "analysis/report/index.qmd" "$post" "blog post (index.qmd)"
}

# book (R7): multi-chapter Quarto book under analysis/book/, self-contained
# (no root symlink); carries its own media/images.
_scaffold_book_project() {
    mkdir -p analysis/book/media/images
    local book_yml='project:
  type: book

book:
  title: "Book Title"
  author: "'"${AUTHOR_NAME:-Your Name}"'"
  chapters:
    - index.qmd
    - 01-intro.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrbook'
    create_file_if_missing "analysis/book/_quarto.yml" "$book_yml" "book Quarto config"

    local book_index='# Preface {.unnumbered}

Describe the book here. This preface is unnumbered front matter.'
    create_file_if_missing "analysis/book/index.qmd" "$book_index" "book preface"

    local book_ch1='# Introduction

Write the first chapter here. Add chapters as `analysis/book/NN-name.qmd`
and list them under `book.chapters` in `_quarto.yml`.'
    create_file_if_missing "analysis/book/01-intro.qmd" "$book_ch1" "book chapter 1"

    create_file_if_missing "analysis/book/references.bib" \
        "% Add BibTeX entries here; cite them in chapters with [@key]." \
        "book bibliography"
}

# simulation: a seeded, parallel-ready starter script.
_scaffold_simulation_script() {
    local sim='# Simulation entry point (archetype: simulation).
# Reproducible stochastics: set the RNG seed explicitly. RNGkind is pinned in
# .Rprofile. For parallel runs use parallel::clusterSetRNGStream() or
# future + furrr with a single global seed.
set.seed(1)

run_simulation <- function(n = 1000L) {
  # Replace with the study design.
  mean(rnorm(n))
}

if (sys.nframe() == 0L) {
  result <- run_simulation()
  cat("simulation result:", result, "\n")
}'
    create_file_if_missing "analysis/scripts/simulation.R" "$sim" "simulation starter"
}

# The one engine: read the spec for ARCHETYPE and dispatch the entry scaffold
# plus any symlink topology. WITH_EXAMPLES gives an otherwise entry-less
# archetype (package) an example document.
apply_archetype_scaffold() {
    local a="${ARCHETYPE:-analysis}"
    local entry
    entry="$(archetype_spec "$a" render_entry)"
    if [[ "${WITH_EXAMPLES:-false}" == "true" && "$entry" == "none" ]]; then
        entry="analysis_index"
    fi
    case "$entry" in
        report_rmd)     _scaffold_report_rmd ;;
        analysis_index) _scaffold_analysis_index ;;
        blog_index)     _scaffold_blog_index ;;
        book)           _scaffold_book_project ;;
        simulation)     _scaffold_simulation_script ;;
        none)           : ;;
    esac
    if [[ "$(archetype_spec "$a" symlinks)" == "blog" ]]; then
        create_archetype_symlinks "blog"
    fi
    return 0
}

#=============================================================================
# ANALYSIS TEMPLATES
#=============================================================================

create_analysis_files() {
    log_debug "Creating analysis structure..."

    # Data README
    if [[ -f "${ZZCOLLAB_TEMPLATES_DIR:-}/data_README.md" ]]; then
        install_template "data_README.md" "analysis/data/README.md" "data README"
    fi

    # Archetype-driven scaffolding, dispatched from the declarative spec.
    apply_archetype_scaffold
}

#=============================================================================
# DEVELOPMENT TOOLS
#=============================================================================

create_devtools() {
    log_debug "Creating development tools..."

    # Makefile
    if [[ -f "${ZZCOLLAB_TEMPLATES_DIR:-}/Makefile" ]]; then
        install_template "Makefile" "Makefile" "Makefile"
    fi

    # CITATION.cff — machine-readable citation metadata for the project
    if [[ -f "${ZZCOLLAB_TEMPLATES_DIR:-}/CITATION.cff" ]]; then
        install_template "CITATION.cff" "CITATION.cff" "CITATION.cff"
    fi

    # devcontainer.json — VS Code / GitHub Codespaces container configuration
    if [[ -f "${ZZCOLLAB_TEMPLATES_DIR:-}/devcontainer.json" ]]; then
        mkdir -p ".devcontainer"
        install_template "devcontainer.json" ".devcontainer/devcontainer.json" "devcontainer config"
    fi

    # .gitignore
    local gitignore_content='.Rproj.user
.Rhistory
.RData
.Ruserdata
*.Rproj
.DS_Store
inst/doc
renv/library/
renv/staging/
.make/
.zzcollab.log'
    create_file_if_missing ".gitignore" "$gitignore_content" ".gitignore"

    # .Rbuildignore
    local rbuildignore_content='^.*\.Rproj$
^\.Rproj\.user$
^analysis$
^docs$
^\.github$
^renv$
^renv\.lock$
^Makefile$
^Dockerfile$
^\.dockerignore$'
    create_file_if_missing ".Rbuildignore" "$rbuildignore_content" ".Rbuildignore"

    log_success "Development tools created"
}

#=============================================================================
# RENV SETUP
#=============================================================================

create_renv_setup() {
    log_debug "Setting up renv..."

    # Check if renv.lock already exists
    if [[ -f "renv.lock" ]]; then
        log_info "renv.lock already exists, skipping renv init"
        return 0
    fi

    # .Rprofile from template (contains renv activation, auto-restore, auto-snapshot)
    if [[ -f "${ZZCOLLAB_TEMPLATES_DIR:-}/.Rprofile" ]]; then
        install_template ".Rprofile" ".Rprofile" ".Rprofile"
    else
        log_warn "Template .Rprofile not found at ${ZZCOLLAB_TEMPLATES_DIR:-}/.Rprofile"
    fi
    return 0
}

# CI workflows are installed by create_ci_workflows() in modules/github.sh
# (sourced after this module), which dispatches on the configured forge
# (GitHub Actions or GitLab CI) and which setup_project() calls.

#=============================================================================
# DOCUMENTATION FILES
#=============================================================================

create_docs_files() {
    log_debug "Creating documentation files..."

    # ZZCOLLAB_USER_GUIDE.md
    if [[ -f "${ZZCOLLAB_TEMPLATES_DIR:-}/ZZCOLLAB_USER_GUIDE.md" ]]; then
        install_template "ZZCOLLAB_USER_GUIDE.md" "docs/ZZCOLLAB_USER_GUIDE.md" "user guide"
    fi

    log_success "Documentation files created"
    return 0
}

#=============================================================================
# RENDER-STAMP TOOLS
#=============================================================================

# Function: create_tools_directory
# Purpose: Install the vendored render-stamp helpers into tools/.
#          Invoked by cmd_quickstart for document-rendering profiles
#          and by `zzc tools` for retrofitting an existing project.
#          copy_template_file skips files that already exist, so a
#          project carrying its own tools/ is left untouched.
create_tools_directory() {
    log_debug "Installing render-stamp tools..."

    install_template "tools/stamp.tex" "tools/stamp.tex" \
        "stamp preamble"
    install_template "tools/stamp-render.R" "tools/stamp-render.R" \
        "render-stamp helper"
    install_template "tools/render.sh" "tools/render.sh" \
        "render wrapper"
    install_template "tools/README.md" "tools/README.md" \
        "tools README"

    [[ -f tools/render.sh ]] && chmod +x tools/render.sh

    log_success "Render-stamp tools installed in tools/"
    return 0
}

#=============================================================================
# MAIN SETUP FUNCTION
#=============================================================================

setup_project() {
    log_info "Setting up project structure..."

    create_directory_structure || return 1
    # R9: a bare/prose compendium omits the R-package skeleton (R/, tests/,
    # DESCRIPTION, NAMESPACE); the analysis workspace and docs still scaffold.
    if [[ "${ZZCOLLAB_BARE:-false}" != "true" ]]; then
        create_r_package_files || return 1
        create_test_infrastructure || return 1
    else
        log_info "Bare compendium: skipping R-package skeleton (R/, tests/, DESCRIPTION, NAMESPACE)"
    fi
    create_analysis_files || return 1
    create_devtools || return 1
    create_renv_setup || return 1
    create_ci_workflows || return 1
    create_docs_files || return 1

    # Adopt-mode: Dockerfile is written by the docker module, not here.

    log_success "Project setup complete"
    return 0
}

#=============================================================================
# MODULE LOADED
#=============================================================================

