#!/bin/bash
set -euo pipefail
##############################################################################
# ZZCOLLAB PROJECT MODULE (Consolidated)
##############################################################################
#
# PURPOSE: Project structure creation and R package setup
#          - Directory structure (rrtools framework)
#          - R package files (DESCRIPTION, NAMESPACE, tests)
#          - Analysis templates
#          - Development tools (Makefile, .gitignore)
#
# DEPENDENCIES: core.sh, templates.sh
##############################################################################

require_module "core" "templates"

#=============================================================================
# DIRECTORY STRUCTURE
#=============================================================================

create_directory_structure() {
    log_debug "Creating directory structure..."

    local dirs=(
        "R"
        "man"
        "tests"
        "tests/testthat"
        "vignettes"
        "analysis"
        "analysis/data"
        "analysis/data/raw_data"
        "analysis/data/derived_data"
        "analysis/report"
        "analysis/figures"
        "analysis/tables"
        "analysis/scripts"
        "docs"
        ".github"
        ".github/workflows"
    )

    for dir in "${dirs[@]}"; do
        if mkdir -p "$dir"; then
            track_directory "$dir"
        else
            log_error "Failed to create directory: $dir"
            return 1
        fi
    done

    log_success "Created ${#dirs[@]} directories"
}

#=============================================================================
# R PACKAGE FILES
#=============================================================================

create_r_package_files() {
    local pkg_name="${PKG_NAME:-$(basename "$(pwd)")}"

    log_debug "Creating R package files..."

    # DESCRIPTION
    if [[ -f "${ZZCOLLAB_TEMPLATES_DIR:-}/DESCRIPTION" ]]; then
        install_template "DESCRIPTION" "DESCRIPTION" "DESCRIPTION file"
    else
        create_description_file "$pkg_name"
    fi

    # NAMESPACE
    local namespace_content='# Generated by roxygen2: do not edit by hand
exportPattern("^[[:alpha:]]+")'
    create_file_if_missing "NAMESPACE" "$namespace_content" "NAMESPACE file"

    # LICENSE
    local license_content="YEAR: $(date +%Y)
COPYRIGHT HOLDER: ${AUTHOR_NAME:-Author}"
    create_file_if_missing "LICENSE" "$license_content" "LICENSE file"

    log_success "R package files created"
}

create_description_file() {
    local pkg_name="$1"
    local content="Package: ${pkg_name}
Title: ${pkg_name} Data Analysis
Version: 0.0.0.9000
Authors@R: person(\"${AUTHOR_NAME:-Author}\", email = \"${AUTHOR_EMAIL:-author@example.com}\", role = c(\"aut\", \"cre\"))
Description: Data analysis workspace for ${pkg_name}.
License: GPL-3
Encoding: UTF-8
Roxygen: list(markdown = TRUE)
RoxygenNote: 7.2.0
Imports:
    renv
Config/testthat/edition: 3"
    create_file_if_missing "DESCRIPTION" "$content" "DESCRIPTION file"
}

#=============================================================================
# TEST INFRASTRUCTURE
#=============================================================================

create_test_infrastructure() {
    log_debug "Creating test infrastructure..."

    # testthat.R setup file
    local testthat_setup='library(testthat)
library('"${PKG_NAME:-$(basename "$(pwd)")}"')
test_check("'"${PKG_NAME:-$(basename "$(pwd)")}"'")'
    create_file_if_missing "tests/testthat.R" "$testthat_setup" "testthat setup"

    # Example test file
    local test_example='test_that("package loads correctly", {
  expect_true(TRUE)
})'
    create_file_if_missing "tests/testthat/test-basic.R" "$test_example" "example test"

    log_success "Test infrastructure created"
}

#=============================================================================
# ANALYSIS TEMPLATES
#=============================================================================

create_analysis_files() {
    log_debug "Creating analysis structure..."

    # Data README
    if [[ -f "${ZZCOLLAB_TEMPLATES_DIR:-}/data_README.md" ]]; then
        install_template "data_README.md" "analysis/data/README.md" "data README"
    fi

    # Only create examples if requested
    if [[ "${WITH_EXAMPLES:-false}" == "true" ]]; then
        install_template "report.Rmd" "analysis/report/report.Rmd" "report template" 2>/dev/null || true
        install_template "references.bib" "analysis/report/references.bib" "bibliography" 2>/dev/null || true
        log_success "Example analysis files created"
    fi
}

#=============================================================================
# DEVELOPMENT TOOLS
#=============================================================================

create_devtools() {
    log_debug "Creating development tools..."

    # Makefile
    if [[ -f "${ZZCOLLAB_TEMPLATES_DIR:-}/Makefile" ]]; then
        install_template "Makefile" "Makefile" "Makefile"
    fi

    # .gitignore
    local gitignore_content='.Rproj.user
.Rhistory
.RData
.Ruserdata
*.Rproj
.DS_Store
inst/doc
renv/library/
renv/staging/
.zzcollab.log'
    create_file_if_missing ".gitignore" "$gitignore_content" ".gitignore"

    # .Rbuildignore
    local rbuildignore_content='^.*\.Rproj$
^\.Rproj\.user$
^analysis$
^docs$
^\.github$
^renv$
^renv\.lock$
^Makefile$
^Dockerfile$
^\.dockerignore$'
    create_file_if_missing ".Rbuildignore" "$rbuildignore_content" ".Rbuildignore"

    log_success "Development tools created"
}

#=============================================================================
# RENV SETUP
#=============================================================================

create_renv_setup() {
    log_debug "Setting up renv..."

    # Check if renv.lock already exists
    if [[ -f "renv.lock" ]]; then
        log_info "renv.lock already exists, skipping renv init"
        return 0
    fi

    # .Rprofile from template (contains renv activation, auto-restore, auto-snapshot)
    if [[ -f "${ZZCOLLAB_TEMPLATES_DIR:-}/.Rprofile" ]]; then
        cp "${ZZCOLLAB_TEMPLATES_DIR}/.Rprofile" .Rprofile
        log_debug "Created .Rprofile from template"
    else
        log_warn "Template .Rprofile not found at ${ZZCOLLAB_TEMPLATES_DIR:-}/.Rprofile"
    fi
    return 0
}

#=============================================================================
# GITHUB WORKFLOWS
#=============================================================================

create_github_workflows() {
    log_debug "Creating GitHub workflows..."

    if [[ -f "${ZZCOLLAB_TEMPLATES_DIR:-}/workflows/r-package.yml" ]]; then
        install_template "workflows/r-package.yml" ".github/workflows/r-package.yml" "R package workflow"
    fi

    log_success "GitHub Actions workflows created"
    return 0
}

#=============================================================================
# MAIN SETUP FUNCTION
#=============================================================================

setup_project() {
    log_info "Setting up project structure..."

    # Initialize manifest tracking before creating any files
    init_manifest || return 1

    create_directory_structure || return 1
    create_r_package_files || return 1
    create_test_infrastructure || return 1
    create_analysis_files || return 1
    create_devtools || return 1
    create_renv_setup || return 1
    create_github_workflows || return 1

    log_success "Project setup complete"
    return 0
}

#=============================================================================
# MODULE LOADED
#=============================================================================

readonly ZZCOLLAB_PROJECT_LOADED=true
readonly ZZCOLLAB_STRUCTURE_LOADED=true
readonly ZZCOLLAB_ANALYSIS_LOADED=true
readonly ZZCOLLAB_RPACKAGE_LOADED=true
readonly ZZCOLLAB_DEVTOOLS_LOADED=true
