#!/bin/bash
set -euo pipefail
##############################################################################
# ZZCOLLAB R PACKAGE MODULE
##############################################################################
# 
# PURPOSE: R package structure creation and management
#          - DESCRIPTION file with package metadata
#          - NAMESPACE file for exports
#          - R project file configuration
#          - Test infrastructure setup
#          - License and documentation
#          - renv package management setup
#
# DEPENDENCIES: core.sh (logging), templates.sh (file creation)
#
# TRACKING: All created files are tracked for uninstall capability
##############################################################################

# Validate required modules are loaded
require_module "core" "templates"

#=============================================================================
# MANIFEST TRACKING FUNCTIONS
#=============================================================================

# Tracking functions are now provided by core.sh

#=============================================================================
# R PACKAGE CORE FILES CREATION (extracted from lines 418-477)
#=============================================================================

# Function: create_core_files
# Purpose: Creates all essential R package files and structure
# Creates:
#   - DESCRIPTION file with package metadata
#   - LICENSE file with GPL-3 license information
#   - NAMESPACE file for function exports
#   - R project file (.Rproj) with development settings
#   - R utility functions from template
#   - Test infrastructure (testthat framework)
#   - Basic unit tests for included functions
#
# Dependencies: Requires PKG_NAME global variable to be set
# Template Usage: Uses DESCRIPTION and R/utils.R templates
# Tracking: All created files are tracked in manifest for uninstall
create_core_files() {
    local pkg_name="$PKG_NAME"
    local year=$(date +%Y)

    log_debug "Creating core R package files..."

    # DESCRIPTION file - R package metadata and dependencies
    # Generate dynamically based on Docker profile to ensure package compatibility
    log_debug "Generating DESCRIPTION file for profile: ${PROFILE_NAME}"

    local description_content
    description_content=$(generate_description_from_profile "${PROFILE_NAME}")

    if [[ $? -ne 0 ]] || [[ -z "$description_content" ]]; then
        log_warn "Failed to generate DESCRIPTION from profile, falling back to template"
        local description_template
        description_template=$(get_description_template)

        if ! install_template "$description_template" "DESCRIPTION" "DESCRIPTION file" "Created DESCRIPTION file from template"; then
            log_error "Failed to create DESCRIPTION file"
            return 1
        fi
    else
        # Write the dynamically generated DESCRIPTION
        echo "$description_content" > DESCRIPTION
        track_file "DESCRIPTION"
        log_success "Created DESCRIPTION file from profile: ${PROFILE_NAME}"
    fi

    # .Rbuildignore file - Specifies files to exclude from R package build
    # Essential for excluding symbolic links and development files
    if ! install_template ".Rbuildignore" ".Rbuildignore" ".Rbuildignore file" "Created .Rbuildignore file with exclusion patterns"; then
        log_error "Failed to create .Rbuildignore file"
        return 1
    fi

    # LICENSE file - GPL-3 license information
    # Note: GPL-3 doesn't require a separate LICENSE file, but we create a reference note
    local license_content="This package is licensed under GPL-3.
See https://www.gnu.org/licenses/gpl-3.0.en.html for details."
    
    if create_file_if_missing "LICENSE" "$license_content" "LICENSE file"; then
        track_file "LICENSE"
        log_debug "Created LICENSE file with GPL-3 reference"
    else
        log_error "Failed to create LICENSE file"
        return 1
    fi

    # NAMESPACE file - Controls which functions are exported to users
    # Generated by roxygen2, but we provide a basic version with essential exports
    local namespace_content="# Generated by roxygen2: do not edit by hand
"
    
    if create_file_if_missing "NAMESPACE" "$namespace_content" "NAMESPACE file"; then
        track_file "NAMESPACE"
        log_debug "Created NAMESPACE file with function exports"
    else
        log_error "Failed to create NAMESPACE file"
        return 1
    fi

    # Copy R utility functions from template
    # Template contains example functions and proper roxygen2 documentation
    if ! install_template "R/utils.R" "R/utils.R" "R utility functions" "Created R utility functions from template"; then
        log_error "Failed to create R utility functions"
        return 1
    fi

    # Create test infrastructure using testthat framework
    # testthat is the standard R testing framework
    
    # Main test runner file
    # Ensures tests directory exists (should already exist from structure module)
    safe_mkdir "tests" "tests directory"
    local testthat_runner="library(testthat)
library($pkg_name)

test_check(\"$pkg_name\")"
    
    if create_file_if_missing "tests/testthat.R" "$testthat_runner" "testthat runner"; then
        track_file "tests/testthat.R"
        log_debug "Created testthat test runner"
    else
        log_error "Failed to create testthat runner"
        return 1
    fi

    # Basic test file for utility functions
    # Ensures tests/testthat directory exists (should already exist from structure module)
    safe_mkdir "tests/testthat" "testthat directory"
    local test_utils="test_that(\"package loads correctly\", {
  expect_true(TRUE)
})"
    
    if create_file_if_missing "tests/testthat/test-utils.R" "$test_utils" "utility function tests"; then
        track_file "tests/testthat/test-utils.R"
        log_debug "Created basic utility function tests"
    else
        log_error "Failed to create utility tests"
        return 1
    fi
    
    # Create integration tests directory and copy template integration tests
    safe_mkdir "tests/integration" "integration tests directory"
    
    # Copy integration test templates (optional)
    install_template "tests/integration/test-data-pipeline.R" "tests/integration/test-data-pipeline.R" "data pipeline integration tests" "Created data pipeline integration tests" || true
    
    install_template "tests/integration/test-analysis-scripts.R" "tests/integration/test-analysis-scripts.R" "analysis script integration tests" "Created analysis script integration tests" || true
    
    install_template "tests/integration/test-report-rendering.R" "tests/integration/test-report-rendering.R" "report rendering integration tests" "Created report rendering integration tests" || true
    
    log_success "R package core files created successfully"
}

#=============================================================================
# R ENVIRONMENT MANAGEMENT (extracted from lines 551-559)
#=============================================================================

# Function: create_renv_setup
# Purpose: Creates package validation setup for reproducible environments
# Creates:
#   - validation.sh script for dependency checking (pure shell, no R required)
#   - core.sh, utils.sh, constants.sh modules required by validation.sh
#
# Note: renv/ directory and renv.lock will be created inside the container
# on first run, following the Docker-first philosophy (no host R required)
#
# Tracking: The validation script and its dependencies are tracked for uninstall
create_renv_setup() {
    log_debug "Creating package validation setup..."

    # Note: renv/ directory and activate.R will be created inside container
    # This follows Docker-first philosophy - all R operations happen in containers

    # Install module dependencies first (required by validation.sh)
    local module_files=("core.sh" "utils.sh" "constants.sh" "navigation_scripts.sh")
    for module_file in "${module_files[@]}"; do
        if install_template "modules/$module_file" "modules/$module_file" "validation module" "Created $module_file"; then
            chmod +x "modules/$module_file"
        else
            log_error "Failed to create $module_file"
            return 1
        fi
    done

    # Install validation.sh script (pure shell validation, no R required)
    if install_template "modules/validation.sh" "modules/validation.sh" "package validation script" "Created validation.sh for dependency checking"; then
        chmod +x "modules/validation.sh"
        log_success "Created validation script (no host R required)"
    else
        log_error "Failed to create validation script"
        return 1
    fi
}

#=============================================================================
# R PACKAGE VALIDATION AND UTILITIES
#=============================================================================

# Function: validate_r_package_structure
# Purpose: Verify that all required R package files were created successfully
# Checks: DESCRIPTION, NAMESPACE, R/, tests/, .Rproj file
# Returns: 0 if all files exist, 1 if any are missing
validate_r_package_structure() {
    log_info "Validating R package structure..."
    
    local -r required_files=(
        "DESCRIPTION"
        ".Rbuildignore"
        "NAMESPACE"
        "LICENSE"
        "R/utils.R"
        "tests/testthat.R"
        "tests/testthat/test-utils.R"
    )

    # Use centralized validation function from core.sh
    validate_files_exist "R package structure" "${required_files[@]}"
}

# Function: show_rpackage_summary
# Purpose: Display summary of created R package structure and next steps
show_rpackage_summary() {
    log_info "R package structure summary:"
    cat << 'EOF'
📦 R PACKAGE STRUCTURE CREATED:

├── DESCRIPTION              # Package metadata and dependencies
├── .Rbuildignore           # Files to exclude from package build
├── NAMESPACE               # Function exports (managed by roxygen2)
├── LICENSE                 # GPL-3 license reference
├── R/
│   └── utils.R            # Package functions with documentation
└── tests/
    ├── testthat.R         # Test runner
    └── testthat/
        └── test-utils.R   # Unit tests for package functions

🔧 DEVELOPMENT WORKFLOW:
1. Run 'Rscript setup_renv.R' to initialize package management
2. Edit R/utils.R to add your package functions
3. Use roxygen2 comments to document functions
4. Run devtools::document() to update NAMESPACE and man/
5. Run devtools::test() to run unit tests
6. Run devtools::check() to validate package

📚 KEY COMMANDS:
- devtools::load_all()     # Load package for testing
- devtools::document()     # Generate documentation
- devtools::test()         # Run tests
- devtools::check()        # R CMD check
- renv::status()           # Check package synchronization
- renv::snapshot()         # Update lockfile
EOF
}

#=============================================================================
# RPACKAGE MODULE VALIDATION
#=============================================================================

# Validate that required manifest variables are available
if [[ -z "${MANIFEST_FILE:-}" ]]; then
    log_warn "MANIFEST_FILE not defined - tracking will be disabled"
fi

if [[ -z "${PKG_NAME:-}" ]]; then
    log_error "PKG_NAME not defined - required for R package creation"
    exit 1
fi


