#!/bin/bash
##############################################################################
# ZZCOLLAB STRUCTURE MODULE
##############################################################################
# 
# PURPOSE: Project structure creation and navigation setup
#          - Directory structure creation with tracking
#          - Symbolic link creation for convenience navigation
#          - Project layout management with uninstall support
#
# DEPENDENCIES: core.sh (for logging functions)
#
# TRACKING: All directories and symlinks created are tracked for uninstall
##############################################################################

# Validate core module is loaded
if [[ "${ZZCOLLAB_CORE_LOADED:-}" != "true" ]]; then
    echo "❌ Error: structure.sh requires core.sh to be loaded first" >&2
    exit 1
fi

#=============================================================================
# MANIFEST TRACKING FUNCTIONS
#=============================================================================

# Tracking functions are now provided by core.sh

#=============================================================================
# DIRECTORY STRUCTURE CREATION (extracted from lines 386-416)
#=============================================================================

# Function: create_directory_structure
# Purpose: Creates the complete directory structure for the R research compendium
# Creates: 18 directories organized for R package development and research workflow
# 
# Directory Layout Created:
#   R/                      - R package functions (exported to users)
#   man/                    - Manual pages (generated by roxygen2)
#   tests/testthat/         - Unit tests using testthat framework
#   vignettes/              - Package vignettes and tutorials
#   data/                   - Data management root directory
#   ├── raw_data/           - Original, unmodified datasets
#   ├── derived_data/       - Processed, analysis-ready data
#   ├── metadata/           - Data dictionaries and documentation
#   └── validation/         - Data quality reports and validation
#   analysis/               - Research analysis components
#   ├── report/              - Research paper (Rmd → PDF)
#   ├── figures/            - Generated plots and visualizations
#   ├── tables/             - Generated statistical tables
#   └── templates/          - Analysis templates and snippets
#   scripts/                - Working R scripts and exploratory analysis
#   archive/                - Archived files and old versions
#   docs/                   - Project documentation
#   .github/workflows/      - GitHub Actions CI/CD pipelines
#
# Error Handling: Fails fast if any directory creation fails
# Tracking: All created directories are tracked in manifest for uninstall
create_directory_structure() {
    log_info "Creating directory structure..."
    
    # Define all directories to create in logical order
    # Each directory serves a specific purpose in the research workflow
    local -r dirs=(
        "R"                      # R package functions
        "man"                    # Manual pages
        "tests/testthat"         # Unit tests with testthat subdirectory
        "vignettes"              # Package vignettes
        "data"                   # Data management root
        "data/raw_data"          # Raw, unmodified data
        "data/derived_data"      # Processed data ready for analysis
        "data/metadata"          # Data documentation and dictionaries
        "data/validation"        # Data quality and validation reports
        "analysis"               # Analysis workflow root
        "analysis/report"         # Research paper development
        "analysis/figures"       # Generated plots and figures
        "analysis/tables"        # Generated tables and summaries
        "analysis/templates"     # Analysis templates and reusable code
        "scripts"                # Working scripts and exploration
        "archive"                # Archived and legacy files
        "docs"                   # Project documentation
        ".github/workflows"      # GitHub Actions CI/CD workflows
    )
    
    # Create each directory and track it for uninstall capability
    for dir in "${dirs[@]}"; do
        # mkdir -p creates parent directories as needed and doesn't fail if directory exists
        if mkdir -p "$dir"; then
            # Track successful directory creation for uninstall manifest
            track_directory "$dir"
            log_info "Created directory: $dir"
        else
            log_error "Failed to create directory: $dir"
            return 1
        fi
    done
    
    log_success "Directory structure created (${#dirs[@]} directories)"
}

#=============================================================================
# NAVIGATION SCRIPTS CREATION (replaces symbolic links)
#=============================================================================

# Function: create_navigation_scripts
# Purpose: Creates navigation_scripts.sh that generates one-letter navigation scripts
# Creates: A single navigation_scripts.sh file that can create navigation shortcuts
#
# Navigation Scripts Created:
#   a → ./data                 - Quick access to data directory
#   n → ./analysis             - Quick access to analysis directory
#   f → ./analysis/figures     - Quick access to figures
#   t → ./analysis/tables      - Quick access to tables
#   s → ./scripts              - Quick access to scripts
#   m → ./man                  - Quick access to manual pages
#   e → ./tests                - Quick access to tests
#   o → ./docs                 - Quick access to documentation
#   c → ./archive              - Quick access to archive
#   p → ./analysis/report      - Quick access to report directory
#
# Usage Examples:
#   ./navigation_scripts.sh    # Create navigation scripts
#   ./a                        # Go to data directory
#   ./n                        # Go to analysis directory
#
# Note: Creates shell scripts instead of symbolic links to avoid devtools::check() issues
create_navigation_scripts() {
    log_info "Creating navigation scripts..."
    
    # Create navigation_scripts.sh that generates one-letter navigation scripts
    cat > navigation_scripts.sh << 'EOF'
#!/bin/bash
# Navigation Scripts Generator
# Creates one-letter shell scripts for quick directory navigation
# Usage: ./navigation_scripts.sh

echo "Creating navigation scripts..."

# Remove existing navigation scripts
rm -f a n f t s m e o c p

# Create navigation scripts for existing directories
if [[ -d "./data" ]]; then
    cat > a << 'SCRIPT'
#!/bin/bash
cd ./data
exec "$SHELL"
SCRIPT
    chmod +x a
    echo "Created: a → ./data"
fi

if [[ -d "./analysis" ]]; then
    cat > n << 'SCRIPT'
#!/bin/bash
cd ./analysis
exec "$SHELL"
SCRIPT
    chmod +x n
    echo "Created: n → ./analysis"
fi

if [[ -d "./analysis/figures" ]]; then
    cat > f << 'SCRIPT'
#!/bin/bash
cd ./analysis/figures
exec "$SHELL"
SCRIPT
    chmod +x f
    echo "Created: f → ./analysis/figures"
fi

if [[ -d "./analysis/tables" ]]; then
    cat > t << 'SCRIPT'
#!/bin/bash
cd ./analysis/tables
exec "$SHELL"
SCRIPT
    chmod +x t
    echo "Created: t → ./analysis/tables"
fi

if [[ -d "./scripts" ]]; then
    cat > s << 'SCRIPT'
#!/bin/bash
cd ./scripts
exec "$SHELL"
SCRIPT
    chmod +x s
    echo "Created: s → ./scripts"
fi

if [[ -d "./man" ]]; then
    cat > m << 'SCRIPT'
#!/bin/bash
cd ./man
exec "$SHELL"
SCRIPT
    chmod +x m
    echo "Created: m → ./man"
fi

if [[ -d "./tests" ]]; then
    cat > e << 'SCRIPT'
#!/bin/bash
cd ./tests
exec "$SHELL"
SCRIPT
    chmod +x e
    echo "Created: e → ./tests"
fi

if [[ -d "./docs" ]]; then
    cat > o << 'SCRIPT'
#!/bin/bash
cd ./docs
exec "$SHELL"
SCRIPT
    chmod +x o
    echo "Created: o → ./docs"
fi

if [[ -d "./archive" ]]; then
    cat > c << 'SCRIPT'
#!/bin/bash
cd ./archive
exec "$SHELL"
SCRIPT
    chmod +x c
    echo "Created: c → ./archive"
fi

if [[ -d "./analysis/report" ]]; then
    cat > p << 'SCRIPT'
#!/bin/bash
cd ./analysis/report
exec "$SHELL"
SCRIPT
    chmod +x p
    echo "Created: p → ./analysis/report"
fi

echo "Navigation scripts created successfully!"
echo "Usage: ./a (data), ./n (analysis), ./p (report), etc."
EOF

    chmod +x navigation_scripts.sh
    log_success "Navigation scripts generator created: navigation_scripts.sh"
    log_info "Run './navigation_scripts.sh' to create navigation shortcuts"
}

#=============================================================================
# STRUCTURE VALIDATION AND REPORTING
#=============================================================================

# Function: validate_directory_structure
# Purpose: Verify that all required directories were created successfully
# Returns: 0 if all directories exist, 1 if any are missing
validate_directory_structure() {
    log_info "Validating directory structure..."
    
    local -r required_dirs=(
        "R" "man" "tests/testthat" "vignettes" "data" "data/raw_data"
        "data/derived_data" "data/metadata" "data/validation" "analysis"
        "analysis/report" "analysis/figures" "analysis/tables" "analysis/templates"
        "scripts" "archive" "docs" ".github/workflows"
    )
    
    local missing_dirs=()
    for dir in "${required_dirs[@]}"; do
        if [[ ! -d "$dir" ]]; then
            missing_dirs+=("$dir")
        fi
    done
    
    if [[ ${#missing_dirs[@]} -eq 0 ]]; then
        log_success "All required directories exist"
        return 0
    else
        log_error "Missing directories: ${missing_dirs[*]}"
        return 1
    fi
}

# Function: show_structure_summary
# Purpose: Display a summary of the created project structure
show_structure_summary() {
    log_info "Project structure summary:"
    cat << 'EOF'
📁 PROJECT STRUCTURE CREATED:

├── R/                     # Package functions (exported to users)
├── man/                   # Manual pages (generated by roxygen2)  
├── tests/testthat/        # Unit tests using testthat framework
├── vignettes/             # Package vignettes and tutorials
├── data/                  # Data management
│   ├── raw_data/          # Original, unmodified datasets
│   ├── derived_data/      # Processed, analysis-ready data
│   ├── metadata/          # Data dictionaries and documentation
│   └── validation/        # Data quality reports
├── analysis/              # Research analysis workflow
│   ├── report/             # Research paper (Rmd → PDF)
│   ├── figures/           # Generated plots and visualizations
│   ├── tables/            # Generated statistical tables
│   └── templates/         # Analysis templates
├── scripts/               # Working R scripts and exploration
├── archive/               # Archived files and old versions
├── docs/                  # Project documentation
├── .github/workflows/     # GitHub Actions CI/CD pipelines
└── Symbolic links (a→data, n→analysis, p→paper, etc.)

🔗 QUICK NAVIGATION:
   cd a  →  data/           cd n  →  analysis/
   cd f  →  figures/        cd t  →  tables/
   cd s  →  scripts/        cd p  →  report/
   cd m  →  man/            cd e  →  tests/
   cd o  →  docs/           cd c  →  archive/
EOF
}

#=============================================================================
# STRUCTURE MODULE VALIDATION
#=============================================================================

# Validate that required manifest variables are available
if [[ -z "${MANIFEST_FILE:-}" ]]; then
    log_warn "MANIFEST_FILE not defined - tracking will be disabled"
fi

if [[ -z "${MANIFEST_TXT:-}" ]]; then
    log_warn "MANIFEST_TXT not defined - fallback tracking will be disabled"
fi

# Set structure module loaded flag
readonly ZZCOLLAB_STRUCTURE_LOADED=true

log_info "Structure module loaded successfully"