name: Data Validation

# 🎯 What this does:
# - Validates data file structure and integrity
# - Checks for missing/corrupt data files
# - Verifies key variables exist
#
# 📦 When to use: Research projects with data files

on:
  push:
    branches: [main, master]
    paths:
      - 'analysis/data/**'
      - 'data/**'
  workflow_dispatch:

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Restore R packages
        run: Rscript -e "renv::restore()"

      - name: Check data directory structure
        run: |
          for dir in analysis/data/raw_data analysis/data/derived_data data; do
            if [ -d "$dir" ]; then
              echo "✅ $dir exists"
            fi
          done

      - name: Validate data files
        run: |
          Rscript -e '
          cat("## Data Validation\n\n", file=Sys.getenv("GITHUB_STEP_SUMMARY"))

          # Check derived data
          derived_files <- list.files(
            "analysis/data/derived_data",
            pattern = "\\.(RData|rds)$",
            full.names = TRUE
          )

          for (f in derived_files) {
            size <- file.info(f)$size / 1024
            cat(sprintf("- ✅ %s (%.1f KB)\n", basename(f), size),
                file=Sys.getenv("GITHUB_STEP_SUMMARY"), append=TRUE)
          }
          '
