name: Matrix Testing

# 🎯 What this does:
# - Tests your package across multiple OS (Ubuntu, macOS, Windows)
# - Tests across multiple R versions
# - Ensures cross-platform compatibility
#
# 📦 When to use: If collaborators use different operating systems

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
  schedule:
    - cron: '0 9 * * 1'  # Weekly on Monday

jobs:
  test-matrix:
    name: ${{ matrix.os }} (R-${{ matrix.r }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        r: ['release', 'devel']

    steps:
      - uses: actions/checkout@v4

      - name: Set up R ${{ matrix.r }}
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.r }}

      - name: Restore R packages
        run: Rscript -e "renv::restore()"

      - name: Test package loads
        run: Rscript -e "library(YOURPACKAGE); cat('✅ Package loaded\n')"

      - name: Run tests
        continue-on-error: true
        run: Rscript -e "testthat::test_dir('tests/testthat')"
