name: Analysis Workflow (Data Science)

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:  # Manual trigger

jobs:
  analysis:
    runs-on: ubuntu-latest
    container: rocker/tidyverse:latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Check renv synchronization
        run: |
          Rscript validate_package_environment.R --quiet --fail-on-issues
      
      - name: Validate data analysis structure
        run: |
          Rscript -e "if (dir.exists('data')) cat('✅ data/ directory found\\n')"
          Rscript -e "if (dir.exists('analysis')) cat('✅ analysis/ directory found\\n')"
          Rscript -e "if (dir.exists('outputs')) cat('✅ outputs/ directory found\\n')"
          Rscript -e "if (file.exists('renv.lock')) cat('✅ renv.lock found\\n')"
      
      - name: Run data validation scripts
        run: |
          if [ -f "scripts/validate_data.R" ]; then
            Rscript scripts/validate_data.R
          else
            echo "No data validation script found"
          fi
      
      - name: Run exploratory analysis
        run: |
          if [ -f "scripts/01_exploratory_analysis.R" ]; then
            Rscript scripts/01_exploratory_analysis.R
          else
            echo "No exploratory analysis script found"
          fi
      
      - name: Run statistical modeling
        run: |
          if [ -f "scripts/02_statistical_modeling.R" ]; then
            Rscript scripts/02_statistical_modeling.R
          else
            echo "No statistical modeling script found"
          fi

      - name: Run model validation
        run: |
          if [ -f "scripts/03_model_validation.R" ]; then
            Rscript scripts/03_model_validation.R
          else
            echo "No model validation script found"
          fi

      - name: Generate analysis reports
        run: |
          # Render reports from reports/ directory
          if [ -d "reports" ]; then
            find reports -name "*.Rmd" -exec Rscript -e "rmarkdown::render('{}')" \;
          fi
          # Render dashboard and automated reports from scripts/
          if [ -f "scripts/04_interactive_dashboard.Rmd" ]; then
            Rscript -e "rmarkdown::render('scripts/04_interactive_dashboard.Rmd')"
          fi
          if [ -f "scripts/05_automated_report.Rmd" ]; then
            Rscript -e "rmarkdown::render('scripts/05_automated_report.Rmd')"
          fi
      
      - name: Run targets pipeline (if present)
        run: |
          if [ -f "_targets.R" ]; then
            Rscript -e "targets::tar_make()"
          else
            echo "No targets pipeline found"
          fi
      
      - name: Upload analysis outputs
        uses: actions/upload-artifact@v4
        with:
          name: analysis-outputs
          path: |
            outputs/
            reports/*.html
            reports/*.pdf
        if: always()