name: R Package Check

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  check:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - uses: r-lib/actions/setup-pandoc@v2
      
      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: 'release'
          use-public-rspm: true
      
      # Skip renv setup for CI - use standard GitHub Actions dependency management
      # - uses: r-lib/actions/setup-renv@v2
      
      - name: Check renv synchronization
        run: |
          Rscript check_renv_for_commit.R --quiet --fail-on-issues
      
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::rcmdcheck
          cache-version: 5
        timeout-minutes: 8
      
      - uses: r-lib/actions/check-r-package@v2
        with:
          upload-snapshots: true