name: R Package Check (Container)

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  check:
    runs-on: ubuntu-latest
    container: rocker/r-ver:latest
    env:
      ZZCOLLAB_CONTAINER: "true"
      CI_TOOLS_LIB: "/tmp/ci-tools"

    steps:
      - uses: actions/checkout@v4

      - name: Install system dependencies
        run: |
          apt-get update && apt-get install -y jq libcurl4-openssl-dev libssl-dev libxml2-dev

      - name: Validate package files exist
        run: |
          test -f DESCRIPTION || { echo "Missing DESCRIPTION"; exit 1; }
          test -f renv.lock || { echo "Missing renv.lock"; exit 1; }
          echo "Package files validated"

      - name: Cache renv packages
        uses: actions/cache@v3
        with:
          path: ~/.cache/R/renv
          key: renv-${{ hashFiles('renv.lock') }}
          restore-keys: |
            renv-

      - name: Install renv and restore project packages
        run: |
          Rscript -e "install.packages('renv', repos = 'https://cloud.r-project.org')"
          Rscript -e "renv::restore(prompt = FALSE)"

      - name: Install CI tools to separate library
        run: |
          mkdir -p $CI_TOOLS_LIB
          Rscript -e "install.packages(c('rcmdcheck', 'testthat'),
                                       lib = Sys.getenv('CI_TOOLS_LIB'),
                                       repos = 'https://cloud.r-project.org')"

      - name: Run R CMD check
        run: |
          Rscript -e "
            .libPaths(c(Sys.getenv('CI_TOOLS_LIB'), .libPaths()))
            rcmdcheck::rcmdcheck(args = '--no-manual', error_on = 'error')
          "

      - name: Run tests
        continue-on-error: true
        run: |
          Rscript -e "
            .libPaths(c(Sys.getenv('CI_TOOLS_LIB'), .libPaths()))
            if (dir.exists('tests/testthat')) {
              testthat::test_local()
            } else {
              message('No tests/testthat directory found, skipping tests')
            }
          "

      - name: Validate project structure
        run: |
          echo "✅ DESCRIPTION found"
          test -d R && echo "✅ R/ directory found" || echo "⚠️  No R/ directory"
          echo "✅ renv.lock found"
          echo "✅ Project structure validated"
