name: R Package Check (Container)

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  check:
    runs-on: ubuntu-latest
    container: rocker/tidyverse:latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Check renv synchronization
        run: |
          Rscript check_renv_for_commit.R --quiet --fail-on-issues
      
      - name: Run R CMD check
        run: |
          Rscript -e "rcmdcheck::rcmdcheck(args = '--no-manual', error_on = 'warning')"
      
      - name: Run tests
        run: |
          Rscript -e "testthat::test_dir('tests')"
      
      - name: Validate project structure
        run: |
          Rscript -e "if (file.exists('DESCRIPTION')) cat('✅ DESCRIPTION found\n')"
          Rscript -e "if (dir.exists('R')) cat('✅ R/ directory found\n')"
          Rscript -e "if (file.exists('renv.lock')) cat('✅ renv.lock found\n')"
          Rscript -e "cat('✅ Project structure validated\n')"