name: Research Project Check (Minimal)

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  check:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: 'release'
          use-public-rspm: true
      
      - name: Install minimal packages for validation
        run: |
          install.packages(c("renv"), repos = "https://cloud.r-project.org")
        shell: Rscript {0}
      
      - name: Check renv synchronization
        run: |
          Rscript check_renv_for_commit.R --quiet --fail-on-issues
      
      - name: Validate project structure
        run: |
          Rscript -e "if (file.exists('DESCRIPTION')) cat('✅ DESCRIPTION found\n')"
          Rscript -e "if (dir.exists('R')) cat('✅ R/ directory found\n')"
          Rscript -e "if (file.exists('renv.lock')) cat('✅ renv.lock found\n')"
          Rscript -e "cat('✅ Project structure validated\n')"