name: Render Research Paper (HTML)

on:
  workflow_dispatch:  # Manual trigger
  push:
    paths:
      - 'analysis/report/**'
      - 'R/**'

jobs:
  render:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - uses: r-lib/actions/setup-pandoc@v2
      
      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: 'release'
          use-public-rspm: true
      
      - name: Install minimal packages for rendering
        run: |
          install.packages(c("rmarkdown", "bookdown", "knitr"), repos = "https://cloud.r-project.org")
        shell: Rscript {0}
      
      - name: Render report to HTML (CI validation)
        run: |
          Rscript -e "rmarkdown::render('analysis/report/report.Rmd', output_format = 'bookdown::html_document2')"
      
      - name: Upload report
        uses: actions/upload-artifact@v4
        with:
          name: research-report-html
          path: analysis/report/report.html