# ZZCOLLAB VARIANT LIBRARY
# This file contains all available Docker profile definitions.
# Use the add_profile.sh script to easily add any of these to your team's config.yaml

#=============================================================================
# STANDARD RESEARCH ENVIRONMENTS
#=============================================================================

minimal:
  base_image: "rocker/r-ver:latest"
  description: "Minimal development environment with essential R packages"
  packages:
    - "renv"
    - "devtools"
    - "usethis"
    - "testthat"
    - "roxygen2"
  system_deps:
    - "libxml2-dev"
    - "libcurl4-openssl-dev"
    - "libssl-dev"
  category: "standard"
  size: "~800MB"

analysis:
  base_image: "rocker/tidyverse:latest" 
  description: "Data analysis environment with tidyverse and common packages"
  packages:
    - "renv"
    - "devtools"
    - "here"
    - "janitor"
    - "scales"
    - "patchwork"
    - "gt"
    - "DT"
  system_deps:
    - "libxml2-dev"
    - "libcurl4-openssl-dev"
    - "libssl-dev"
  category: "standard"
  size: "~1.2GB"

modeling:
  base_image: "rocker/r-ver:latest"
  description: "Machine learning and statistical modeling environment" 
  packages:
    - "renv"
    - "devtools"
    - "tidyverse"
    - "tidymodels"
    - "xgboost"
    - "randomForest"
    - "glmnet"
    - "caret"
    - "MASS"
    - "mlr3"
  system_deps:
    - "libxml2-dev"
    - "libcurl4-openssl-dev"
    - "libssl-dev"
    - "libgsl-dev"
    - "libblas-dev"
    - "liblapack-dev"
    - "build-essential"
    - "gfortran"
  category: "standard"
  size: "~1.5GB"

publishing:
  base_image: "rocker/verse:latest"
  description: "Document publishing with LaTeX, Quarto, and web tools"
  packages:
    - "renv"
    - "devtools" 
    - "quarto"
    - "bookdown"
    - "blogdown"
    - "distill"
    - "flexdashboard"
    - "shiny"
    - "DT"
    - "plotly"
  system_deps:
    - "pandoc"
    - "texlive-full"
    - "libxml2-dev"
    - "libcurl4-openssl-dev"
    - "libssl-dev"
    - "libv8-dev"
  category: "standard"
  size: "~3GB"

#=============================================================================
# SPECIALIZED DOMAINS
#=============================================================================

bioinformatics:
  base_image: "bioconductor/bioconductor_docker:latest"
  description: "Bioinformatics analysis with Bioconductor packages"
  packages:
    - "renv"
    - "devtools"
    - "BiocManager"
    - "DESeq2"
    - "edgeR"
    - "limma"
    - "GenomicRanges"
    - "Biostrings"
    - "rtracklayer"
  system_deps:
    - "libxml2-dev"
    - "libcurl4-openssl-dev"
    - "libssl-dev"
    - "zlib1g-dev"
    - "libbz2-dev"
    - "liblzma-dev"
  category: "specialized"
  size: "~2GB"

geospatial:
  base_image: "rocker/geospatial:latest"
  description: "Geospatial analysis with sf, terra, and mapping tools"
  packages:
    - "renv"
    - "devtools"
    - "sf"
    - "terra"
    - "leaflet"
    - "mapview"
    - "tmap"
  system_deps:
    - "gdal-bin"
    - "proj-bin"
    - "libgeos-dev"
    - "libproj-dev"
    - "libgdal-dev"
    - "libudunits2-dev"
    - "netcdf-bin"
    - "libxml2-dev"
  category: "specialized"
  size: "~2.5GB"

#=============================================================================
# LIGHTWEIGHT ALPINE VARIANTS
#=============================================================================

alpine_minimal:
  base_image: "velaco/alpine-r:latest"
  description: "Ultra-lightweight Alpine Linux with R (small footprint for CI/CD)"
  packages:
    - "renv"
    - "devtools"
    - "testthat"
  system_deps:
    - "git"
    - "make"
    - "gcc"
    - "g++"
    - "musl-dev"
    - "linux-headers"
    - "curl"
    - "curl-dev"
    - "openssl-dev"
    - "libxml2-dev"
  category: "alpine"
  size: "~200MB"
  notes: "~200MB vs ~1GB for rocker images"

alpine_analysis:
  base_image: "velaco/alpine-r:latest"
  description: "Lightweight Alpine with core data analysis packages"
  packages:
    - "renv"
    - "dplyr"
    - "ggplot2"
    - "readr"
    - "tidyr"
    - "here"
    - "janitor"
    - "devtools"
  system_deps:
    - "git"
    - "make"
    - "gcc"
    - "g++"
    - "gfortran"
    - "musl-dev"
    - "linux-headers"
    - "curl"
    - "curl-dev"
    - "openssl-dev"
    - "libxml2-dev"
  category: "alpine"
  size: "~400MB"

hpc_alpine:
  base_image: "velaco/alpine-r:latest"
  description: "HPC-focused environment with parallel processing and lightweight footprint"
  packages:
    - "renv"
    - "devtools"
    - "parallel"
    - "foreach"
    - "doParallel"
    - "future"
    - "furrr"
    - "data.table"
    - "Rcpp"
    - "RcppArmadillo"
  system_deps:
    - "make"
    - "g++"
    - "git"
    - "gfortran"
    - "musl-dev"
    - "linux-headers"
    - "openblas-dev"
    - "lapack-dev"
    - "cmake"
    - "curl-dev"
    - "openssl-dev"
    - "libxml2-dev"
  category: "alpine"
  size: "~600MB"
  notes: "Optimized for computational efficiency and container orchestration"

#=============================================================================
# R-HUB TESTING ENVIRONMENTS
#=============================================================================

rhub_ubuntu:
  base_image: "rhub/ubuntu-gcc-release:latest"
  description: "R-hub Ubuntu environment for package testing and CI/CD"
  packages:
    - "renv"
    - "devtools"
    - "testthat"
    - "rcmdcheck"
    - "covr"
    - "pkgdown"
    - "roxygen2"
  system_deps:
    - "qpdf"
    - "pandoc"
    - "libxml2-dev"
    - "libcurl4-openssl-dev"
    - "libssl-dev"
    - "libgit2-dev"
  category: "rhub"
  size: "~1GB"
  notes: "Matches CRAN check environment for reliable package testing"

rhub_fedora:
  base_image: "rhub/fedora-gcc-devel:latest" 
  description: "R-hub Fedora environment with latest R-devel for cutting-edge testing"
  packages:
    - "renv"
    - "devtools"
    - "testthat"
    - "rcmdcheck"
    - "roxygen2"
  system_deps:
    - "pandoc"
    - "qpdf"
    - "which"
    - "libxml2-devel"
    - "libcurl-devel"
    - "openssl-devel"
    - "libgit2-devel"
  category: "rhub"
  size: "~1.2GB"
  notes: "Tests against R-devel to catch future compatibility issues"

rhub_windows:
  base_image: "rhub/windows-x86_64-mingw-w64:latest"
  description: "R-hub Windows environment for cross-platform package testing"
  packages:
    - "renv"
    - "devtools"
    - "testthat"
    - "rcmdcheck"
    - "roxygen2"
  system_deps:
    - "qpdf"
  category: "rhub"
  size: "~1.5GB"
  notes: "Tests Windows-specific package behavior without needing Windows"

#=============================================================================
# WEB APPLICATION VARIANTS
#=============================================================================

shiny:
  base_image: "rocker/shiny:latest"
  description: "Shiny Server for interactive R web applications"
  packages:
    - "renv"
    - "devtools"
    - "shiny"
    - "shinydashboard"
    - "DT"
    - "plotly"
    - "htmlwidgets"
    - "flexdashboard"
  system_deps:
    - "libxml2-dev"
    - "libcurl4-openssl-dev"
    - "libssl-dev"
    - "libv8-dev"
  category: "standard"
  size: "~1.8GB"
  notes: "Includes Shiny Server configured for production deployment"

shiny_verse:
  base_image: "rocker/shiny-verse:latest"
  description: "Shiny Server with tidyverse and publishing capabilities"
  packages:
    - "renv"
    - "devtools"
    - "shiny"
    - "shinydashboard"
    - "DT"
    - "plotly"
    - "flexdashboard"
    - "bookdown"
    - "blogdown"
    - "reactable"
    - "crosstalk"
  system_deps:
    - "libxml2-dev"
    - "libcurl4-openssl-dev" 
    - "libssl-dev"
    - "libv8-dev"
    - "pandoc"
  category: "standard"
  size: "~3.5GB"
  notes: "Full-featured Shiny with tidyverse and document publishing capabilities"

#=============================================================================
# GUI/X11 VARIANTS
#=============================================================================

gui_minimal:
  base_image: "rocker/r-ver:latest"
  description: "Minimal R environment with X11/GUI support for desktop applications"
  packages:
    - "renv"
    - "devtools"
    - "usethis"
    - "testthat"
    - "roxygen2"
  system_deps:
    - "libxml2-dev"
    - "libcurl4-openssl-dev"
    - "libssl-dev"
    # X11 and GUI libraries
    - "xorg"
    - "x11-apps"
    - "xauth"
    - "libx11-dev"
    - "libxt-dev"
    - "libcairo2-dev"
    - "libgl1-mesa-dev"
    - "libglu1-mesa-dev"
    - "fonts-dejavu"
    - "fonts-liberation"
    # GUI applications
    - "kitty"
    - "firefox-esr"
    - "gedit"
  category: "gui"
  size: "~1.5GB"
  notes: "Requires XQuartz (macOS) or X11 (Linux). Use 'make docker-zsh-gui' to launch."

gui_analysis:
  base_image: "rocker/tidyverse:latest"
  description: "Data analysis with tidyverse and GUI/X11 support"
  packages:
    - "renv"
    - "devtools"
    - "here"
    - "janitor"
    - "scales"
    - "patchwork"
    - "gt"
    - "DT"
    - "rgl"
    - "plotly"
    - "Cairo"
    - "svglite"
  system_deps:
    - "libxml2-dev"
    - "libcurl4-openssl-dev"
    - "libssl-dev"
    # X11 and GUI libraries
    - "xorg"
    - "x11-apps"
    - "xauth"
    - "libx11-dev"
    - "libxt-dev"
    - "libcairo2-dev"
    - "libgl1-mesa-dev"
    - "libglu1-mesa-dev"
    - "fonts-dejavu"
    - "fonts-liberation"
    # GUI applications
    - "kitty"
    - "firefox-esr"
    - "gedit"
  category: "gui"
  size: "~2.5GB"
  notes: "Full analysis stack with interactive graphics and GUI applications"

gui_rstudio:
  base_image: "rocker/rstudio:latest"
  description: "RStudio Server with X11/GUI support for desktop applications"
  packages:
    - "renv"
    - "devtools"
    - "usethis"
    - "testthat"
    - "roxygen2"
  system_deps:
    - "libxml2-dev"
    - "libcurl4-openssl-dev"
    - "libssl-dev"
    # X11 and GUI libraries
    - "xorg"
    - "x11-apps"
    - "xauth"
    - "libx11-dev"
    - "libxt-dev"
    - "libcairo2-dev"
    - "libgl1-mesa-dev"
    - "libglu1-mesa-dev"
    - "fonts-dejavu"
    - "fonts-liberation"
    # GUI applications
    - "kitty"
    - "firefox-esr"
    - "gedit"
  category: "gui"
  size: "~2GB"
  notes: "RStudio Server (browser) + GUI desktop apps (kitty, firefox) via X11"