# ZZCOLLAB PROFILE LIBRARY
# Organized structure: {base}_{libs}_{packages}
# Base: ubuntu_standard, ubuntu_shiny, alpine_standard
# Libs: standard (no X11), x11 (with X11 forwarding)
# Packages: minimal, analysis, publishing

#=============================================================================
# UBUNTU STANDARD - CLI + optional RStudio via ADD=rstudio
#=============================================================================

ubuntu_standard_minimal:
  base_image: "rocker/r-ver:latest"
  description: "Minimal Ubuntu environment with essential R packages"
  packages:
    - "renv"
    - "devtools"
    - "usethis"
    - "testthat"
    - "roxygen2"
  system_deps:
    - "libxml2-dev"
    - "libcurl4-openssl-dev"
    - "libssl-dev"
    - "libssh2-1-dev"
    - "libfontconfig1-dev"
    - "libharfbuzz-dev"
    - "libfribidi-dev"
    - "libfreetype6-dev"
    - "libpng-dev"
    - "libjpeg-dev"
  category: "ubuntu_standard"
  size: "~800MB"
  notes: "Add RStudio: docker run -e ADD=rstudio -e PASSWORD=pass"

ubuntu_standard_analysis:
  base_image: "rocker/tidyverse:latest"
  description: "Data analysis with tidyverse + modeling packages"
  packages:
    - "renv"
    - "devtools"
    - "here"
    - "janitor"
    - "scales"
    - "patchwork"
    - "gt"
    - "DT"
    # Modeling packages
    - "tidymodels"
    - "xgboost"
    - "randomForest"
    - "glmnet"
    - "caret"
    - "MASS"
  system_deps:
    - "libxml2-dev"
    - "libcurl4-openssl-dev"
    - "libssl-dev"
    - "libssh2-1-dev"
    - "libfontconfig1-dev"
    - "libharfbuzz-dev"
    - "libfribidi-dev"
    - "libfreetype6-dev"
    - "libpng-dev"
    - "libjpeg-dev"
    - "libgsl-dev"
    - "libblas-dev"
    - "liblapack-dev"
    - "gfortran"
  category: "ubuntu_standard"
  size: "~1.5GB"
  notes: "Tidyverse + ML packages. Add RStudio: docker run -e ADD=rstudio"

ubuntu_standard_publishing:
  base_image: "rocker/verse:latest"
  description: "Document publishing with LaTeX, Quarto, and web tools"
  packages:
    - "renv"
    - "devtools"
    - "quarto"
    - "bookdown"
    - "blogdown"
    - "distill"
    - "flexdashboard"
    - "shiny"
    - "DT"
    - "plotly"
  system_deps:
    - "pandoc"
    - "texlive-full"
    - "libxml2-dev"
    - "libcurl4-openssl-dev"
    - "libssl-dev"
    - "libssh2-1-dev"
    - "libv8-dev"
    - "libfontconfig1-dev"
    - "libharfbuzz-dev"
    - "libfribidi-dev"
    - "libfreetype6-dev"
    - "libpng-dev"
    - "libjpeg-dev"
  category: "ubuntu_standard"
  size: "~3GB"
  notes: "Full LaTeX + Quarto publishing stack"

#=============================================================================
# UBUNTU SHINY - Shiny Server for web applications
#=============================================================================

ubuntu_shiny_minimal:
  base_image: "rocker/shiny:latest"
  description: "Shiny Server with minimal packages"
  packages:
    - "renv"
    - "devtools"
    - "shiny"
    - "shinydashboard"
    - "DT"
    - "plotly"
  system_deps:
    - "libxml2-dev"
    - "libcurl4-openssl-dev"
    - "libssl-dev"
    - "libssh2-1-dev"
    - "libcairo2-dev"
    - "libxt-dev"
    - "pandoc"
    - "pandoc-citeproc"
  category: "ubuntu_shiny"
  size: "~1.8GB"
  notes: "Shiny Server on port 3838"

ubuntu_shiny_analysis:
  base_image: "rocker/shiny-verse:latest"
  description: "Shiny Server with tidyverse and publishing capabilities"
  packages:
    - "renv"
    - "devtools"
    - "shiny"
    - "shinydashboard"
    - "DT"
    - "plotly"
    - "flexdashboard"
    - "bookdown"
    - "reactable"
    - "crosstalk"
  system_deps:
    - "libxml2-dev"
    - "libcurl4-openssl-dev"
    - "libssl-dev"
    - "libssh2-1-dev"
    - "libv8-dev"
    - "libcairo2-dev"
    - "libxt-dev"
    - "pandoc"
  category: "ubuntu_shiny"
  size: "~3.5GB"
  notes: "Full-featured Shiny with tidyverse"

#=============================================================================
# UBUNTU X11 - X11 forwarding for GUI applications
#=============================================================================

ubuntu_x11_minimal:
  base_image: "rocker/r-ver:latest"
  description: "Minimal R with X11 support for graphics viewing"
  packages:
    - "renv"
    - "devtools"
    - "usethis"
    - "testthat"
    - "roxygen2"
  system_deps:
    - "libxml2-dev"
    - "libcurl4-openssl-dev"
    - "libssl-dev"
    - "libssh2-1-dev"
    # X11 and GUI libraries
    - "xorg"
    - "x11-apps"
    - "xauth"
    - "libx11-dev"
    - "libxt-dev"
    - "libcairo2-dev"
    - "libgl1-mesa-dev"
    - "libglu1-mesa-dev"
    - "fonts-dejavu"
    - "fonts-liberation"
  category: "ubuntu_x11"
  size: "~1.5GB"
  notes: "Requires XQuartz (macOS) or X11 (Linux). Use 'docker run -e DISPLAY'"

ubuntu_x11_analysis:
  base_image: "rocker/tidyverse:latest"
  description: "Data analysis with tidyverse and X11 support"
  packages:
    - "renv"
    - "devtools"
    - "here"
    - "janitor"
    - "scales"
    - "patchwork"
    - "gt"
    - "DT"
    - "rgl"
    - "plotly"
    - "Cairo"
    - "svglite"
  system_deps:
    - "libxml2-dev"
    - "libcurl4-openssl-dev"
    - "libssl-dev"
    - "libssh2-1-dev"
    # X11 and GUI libraries
    - "xorg"
    - "x11-apps"
    - "xauth"
    - "libx11-dev"
    - "libxt-dev"
    - "libcairo2-dev"
    - "libgl1-mesa-dev"
    - "libglu1-mesa-dev"
    - "fonts-dejavu"
    - "fonts-liberation"
  category: "ubuntu_x11"
  size: "~2.5GB"
  notes: "Full analysis stack with interactive graphics and X11"

#=============================================================================
# ALPINE STANDARD - Lightweight Alpine Linux
#=============================================================================

alpine_standard_minimal:
  base_image: "rhub/r-minimal:latest"
  description: "Ultra-lightweight Alpine Linux with R for CI/CD"
  packages:
    - "renv"
    - "devtools"
    - "testthat"
    - "remotes"
  system_deps:
    - "git"
    - "make"
    - "gcc"
    - "g++"
    - "musl-dev"
    - "linux-headers"
    - "curl-dev"
    - "openssl-dev"
    - "libxml2-dev"
  category: "alpine_standard"
  size: "~200MB"
  notes: "~200MB vs ~800MB for Ubuntu (4x smaller)"

alpine_standard_analysis:
  base_image: "rhub/r-minimal:latest"
  description: "Lightweight Alpine with core data analysis packages"
  packages:
    - "renv"
    - "devtools"
    - "dplyr"
    - "ggplot2"
    - "readr"
    - "tidyr"
    - "here"
    - "janitor"
    - "stringr"
    - "lubridate"
    - "scales"
  system_deps:
    - "git"
    - "make"
    - "gcc"
    - "g++"
    - "gfortran"
    - "musl-dev"
    - "linux-headers"
    - "curl-dev"
    - "openssl-dev"
    - "libxml2-dev"
    - "zlib-dev"
    - "bzip2-dev"
    - "xz-dev"
  category: "alpine_standard"
  size: "~400MB"
  notes: "~400MB vs ~1.5GB for Ubuntu (3.5x smaller)"

#=============================================================================
# ALPINE X11 - Lightweight Alpine with X11 graphics
#=============================================================================

alpine_x11_minimal:
  base_image: "rhub/r-minimal:latest"
  description: "Lightweight Alpine with minimal X11 for base R graphics"
  packages:
    - "renv"
    - "devtools"
    - "testthat"
    - "Cairo"
  system_deps:
    - "git"
    - "make"
    - "gcc"
    - "g++"
    - "musl-dev"
    - "linux-headers"
    - "curl-dev"
    - "openssl-dev"
    - "libxml2-dev"
    # X11 minimal support
    - "xorg-server"
    - "xauth"
    - "libx11"
    - "libx11-dev"
    - "cairo"
    - "cairo-dev"
    - "mesa-dri-gallium"
    - "font-misc-misc"
    - "ttf-dejavu"
  category: "alpine_x11"
  size: "~300MB"
  notes: "Base R plotting with X11. ~5x smaller than ubuntu_x11_minimal"

alpine_x11_analysis:
  base_image: "rhub/r-minimal:latest"
  description: "Lightweight Alpine with X11 support for graphics viewing"
  packages:
    - "renv"
    - "devtools"
    - "dplyr"
    - "ggplot2"
    - "readr"
    - "tidyr"
    - "here"
    - "janitor"
    - "Cairo"
    - "svglite"
  system_deps:
    - "git"
    - "make"
    - "gcc"
    - "g++"
    - "gfortran"
    - "musl-dev"
    - "linux-headers"
    - "curl-dev"
    - "openssl-dev"
    - "libxml2-dev"
    - "zlib-dev"
    - "bzip2-dev"
    - "xz-dev"
    # X11 minimal support
    - "xorg-server"
    - "xauth"
    - "libx11"
    - "libx11-dev"
    - "cairo"
    - "cairo-dev"
    - "mesa-dri-gallium"
    - "font-misc-misc"
    - "ttf-dejavu"
  category: "alpine_x11"
  size: "~500MB"
  notes: "Alpine (~500MB) with minimal X11 vs ubuntu_x11_analysis (~2.5GB). Requires X forwarding."
