name: Render Research Paper

on:
  workflow_dispatch:  # Manual trigger
  push:
    paths:
      - 'analysis/paper/**'
      - 'R/**'

jobs:
  render:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - uses: r-lib/actions/setup-pandoc@v2
      
      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: 'release'
          use-public-rspm: true
      
      - uses: r-lib/actions/setup-renv@v2
      
      - name: Render paper
        run: |
          Rscript -e "rmarkdown::render('analysis/paper/paper.Rmd')"
      
      - name: Upload paper
        uses: actions/upload-artifact@v4
        with:
          name: research-paper
          path: analysis/paper/paper.pdf